In [8]:
import pandas as pd
import numpy as np

import seaborn as sns
%matplotlib inline

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [9]:
#load the dataset
coursetopic_df = pd.read_csv("Coursetopics.csv")
coursetopic_df.head()

   Intro  DataMining  Survey  Cat Data  Regression  Forecast  DOE  SW
0      1           1       0         0           0         0    0   0
1      0           0       1         0           0         0    0   0
2      0           1       0         1           1         0    0   1
3      1           0       0         0           0         0    0   0
4      1           1       0         0           0         0    0   0

In [12]:
frequent_itemsets = apriori(coursetopic_df, min_support=0.05, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2)
rules.head()

C:\Users\user\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Cat Data),(Survey),0.208219,0.186301,0.063014,0.302632,1.62442,0.024222,1.166813
1,(Survey),(Cat Data),0.186301,0.208219,0.063014,0.338235,1.62442,0.024222,1.196469
2,(Regression),(Cat Data),0.208219,0.208219,0.054795,0.263158,1.26385,0.011439,1.074560
3,(Cat Data),(Regression),0.208219,0.208219,0.054795,0.263158,1.26385,0.011439,1.074560
4,(Cat Data),(SW),0.208219,0.221918,0.063014,0.302632,1.36371,0.016806,1.115741